export default {
    49: {padId: 0, hold: false},
    50: {padId: 1, hold: false},
    51: {padId: 2, hold: false},
    52: {padId: 3, hold: false},
    81: {padId: 4, hold: false},
    87: {padId: 5, hold: false},
    69: {padId: 6, hold: false},
    82: {padId: 7, hold: false},
    65: {padId: 8, hold: false},
    83: {padId: 9, hold: false},
    68: {padId: 10, hold: false},
    70: {padId: 11, hold: false},
    90: {padId: 12, hold: false},
    88: {padId: 13, hold: false},
    67: {padId: 14, hold: false},
    86: {padId: 15, hold: false},
}