export default {
    5: {padId: null, cc: "sampleStart"},
    6: {padId: null, cc: "sampleEnd"},
    7: {padId: null, cc: "gain"},
    8: {padId: null, cc: "detune"},
    36: {padId: 12, cc: "note", note: "1"},
    37: {padId: 13, cc: "note", note: "2"},
    38: {padId: 14, cc: "note", note: "3"},
    39: {padId: 15, cc: "note", note: "4"},
    40: {padId: 8, cc: "note", note: "Q"},
    41: {padId: 9, cc: "note", note: "W"},
    42: {padId: 10, cc: "note", note: "E"},
    43: {padId: 11, cc: "note", note: "R"},
    44: {padId: 4, cc: "note", note: "G#2"},
    45: {padId: 5, cc: "note", note: "A2"},
    46: {padId: 6, cc: "note", note: "Bb2"},
    47: {padId: 7, cc: "note", note: "B2"},
    48: {padId: 0, cc: "note", note: "C3"},
    49: {padId: 1, cc: "note", note: "C#3"},
    50: {padId: 2, cc: "note", note: "D3"},
    51: {padId: 3, cc: "note", note: "D#3"},
}
