export default {
    0: {hold: false},
    1: {hold: false},
    2: {hold: false},
    3: {hold: false},
    4: {hold: false},
    5: {hold: false},
    6: {hold: false},
    7: {hold: false},
    8: {hold: false},
    9: {hold: false},
    10: {hold: false},
    11: {hold: false},
    12: {hold: false},
    13: {hold: false},
    14: {hold: false},
    15: {hold: false},
}